services:
  db:
    image: mysql:8.0
    container_name: hiqma_mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_hiqma
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Set to "yes" to match the empty password in .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - hiqma_network

networks:
  hiqma_network:
    driver: bridge

volumes:
  mysql_data:
